FROM python:3-alpine

LABEL author="sathyabhat"
LABEL description="Dockerfile for Python script which prints Hello, Name"
#CMD pwd
#COPY hello-world.py /app/
ENV NAME=Sathya
#CMD python3 /app/hello-world.py
WORKDIR /home/litepoint/Desktop/practical_docker/docker_hello_world
#CMD pwd
#COPY hello-world.py ../ 
COPY hello-world.py .
CMD python3 /home/litepoint/Desktop/practical_docker/docker_hello_world/hello-world.py



