#!/bin/bash
# sample admin menu

echo 'select a task: '
select TASK in 'Check mounts' 'Check disk space' 'Check Memory Usage'
do 
	case $REPLY in 
		1) TASK=mount;;
		2) TASK="df -h";;
		3) TASK="free -m";;
		*) echo ERROR && exit 2;;
	esac
	if [ -n "$TASK" ]
	then
		clear
		$TASK
		break
	else
		echo INVALID CHOICE && 3
	fi
done

